/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hitown_demo_PartsManager */

#ifndef _Included_com_hitown_demo_PartsManager
#define _Included_com_hitown_demo_PartsManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hitown_demo_PartsManager_MSG_JNI_POST
#define com_hitown_demo_PartsManager_MSG_JNI_POST 1000L
/*
 * Class:     com_hitown_demo_PartsManager
 * Method:    openDev
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hitown_demo_PartsManager_openDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hitown_demo_PartsManager
 * Method:    closeDev
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hitown_demo_PartsManager_closeDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hitown_demo_PartsManager
 * Method:    readDev
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_hitown_demo_PartsManager_readDev
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_hitown_demo_PartsManager
 * Method:    writeDev
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_hitown_demo_PartsManager_writeDev
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_hitown_demo_PartsManager
 * Method:    ioctrlDev
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hitown_demo_PartsManager_ioctrlDev
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
